before_script:
  - apt update
  - apt install -y -f zip

build:
  stage: build
  image: node:15.14.0
  cache:
    paths:
      - node_modules
    key: node_modules
  script:
    - yarn
    - ./bin/create-release
  artifacts:
    paths:
      - out/isset-video.zip
    expire_in: 30 days
publish_nightly:
  only:
    - develop
  script:
    - apt install -y -f openssh-client
    - eval "$(ssh-agent)"
    - ssh-add <(echo "${SSH_PRIV_KEY}")
    - mkdir ~/.ssh
    - echo 'Host *' >> ~/.ssh/config
    - echo '  StrictHostKeyChecking no' >> ~/.ssh/config
    - scp out/isset-video.zip wptest@isset122.isset.net:web/WordPress/issetvideoplugin/nightly/${CI_COMMIT_SHA}.zip
    - ssh wptest@isset122.isset.net sh -c "cd ~/web/WordPress/wp-content/plugins/isset-video && rm -rf ~/web/WordPress/wp-content/plugins/isset-video/* && unzip ~/web/WordPress/issetvideoplugin/nightly/${CI_COMMIT_SHA}.zip -d ~/web/WordPress/wp-content/plugins/isset-video"
    - ssh wptest@isset122.isset.net 'chmod -R 755 /home/wptest/web/WordPress/wp-content/plugins/isset-video'
publish_release:
  only:
    - master
  script:
    - apt install -y -f openssh-client
    - eval "$(ssh-agent)"
    - ssh-add <(echo "${SSH_PRIV_KEY_ISSETVIDEO}")
    - mkdir ~/.ssh
    - echo 'Host *' >> ~/.ssh/config
    - echo '  StrictHostKeyChecking no' >> ~/.ssh/config
    - scp out/isset-video.zip issetdotvideo@isset122.isset.net:web/plugin/isset-video.zip