before_script:
  - apt update
  - apt install -y -f zip

build:
  stage: build
  image: node
  cache:
    paths:
      - node_modules
    key: node_modules
  script:
    - yarn
    - ./bin/create-release
  artifacts:
    paths:
      - out/wp-video-publisher.zip
    expire_in: 30 days
publish_nightly:
  script:
    - apt install -y -f openssh-client
    - eval "$(ssh-agent)"
    - ssh-add <(echo "${SSH_PRIV_KEY}")
    - mkdir ~/.ssh
    - echo 'Host *' >> ~/.ssh/config
    - echo '  StrictHostKeyChecking no' >> ~/.ssh/config
    - scp out/wp-video-publisher.zip wptest@isset122.isset.net:web/WordPress/issetvideoplugin/nightly/${CI_COMMIT_SHA}.zip
    - ssh wptest@isset122.isset.net sh -c "cd web/WordPress/wp-content/plugins/wp-video-publisher || exit; rm -rf *; unzip ~/web/WordPress/issetvideoplugin/nightly/${CI_COMMIT_SHA}.zip"