export const UPLOAD_ADDED = 'UPLOAD_ADDED';
export const UPLOAD_IN_PROGRESS = 'UPLOAD_IN_PROGRESS';
export const UPLOAD_ARCHIVING = 'UPLOAD_ARCHIVING';
export const UPLOAD_ARCHIVED = 'UPLOAD_ARCHIVED';
export const UPLOAD_ARCHIVE_FAILED = 'UPLOAD_ARCHIVE_FAILED';